implementing glm_test;
import glm;

public float2 test_float2(float2 v)
{
    return v;
}

public float3 test_float3(float3 v)
{
    return v;
}

public float4 test_float4(float4 v)
{
    return v;
}

public float2x2 test_float2x2(float2x2 m)
{
    return m;
}

public float3x3 test_float3x3(float3x3 m)
{
    return m;
}

public float4x4 test_float4x4(float4x4 m)
{
    return m;
}

public glm.quat.quat test_quaternion(glm.quat.quat q)
{
    return q;
}

public int2 test_int2(int2 v)
{
    return v;
}

public int3 test_int3(int3 v)
{
    return v;
}

public int4 test_int4(int4 v)
{
    return v;
}

public uint2 test_uint2(uint2 v)
{
    return v;
}

public uint3 test_uint3(uint3 v)
{
    return v;
}

public uint4 test_uint4(uint4 v)
{
    return v;
}
